#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)
    lines = []
    lines.append("=" * 70)
    lines.append("  brpc Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")
    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  brpc Version:      {env.get('software_version', 'N/A')}")
        lines.append(f"  GCC Version:       {env.get('gcc_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:           {env.get('kernel', 'N/A')}")
        lines.append("")
    benchmarks = data.get("benchmarks", {})
    primary = benchmarks.get("primary", {})
    if primary:
        lines.append("  --- RPC Echo Benchmark (Primary) ---")
        lines.append(f"  Description:       {primary.get('description', 'N/A')}")
        params = primary.get("parameters", {})
        lines.append(f"  Thread levels:     {params.get('thread_levels', 'N/A')}")
        lines.append(f"  Duration/test:     {params.get('duration_per_test', 'N/A')}s")
        lines.append(f"  Protocol:           {params.get('echo_protocol', 'N/A')}")
        lines.append("")
        rs = primary.get("results_summary", {})
        header = "    {:<14} {:>12} {:>12} {:>12} {:>12} {:>12}".format("threads", "QPS", "avg(us)", "p50(us)", "p99(us)", "p999(us)")
        lines.append(header)
        lines.append("    " + "-" * (len(header) - 4))
        for tl in sorted(rs.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
            e = rs[tl]
            if isinstance(e, dict) and e:
                lines.append("    {:<14} {:>12.2f} {:>12.2f} {:>12.2f} {:>12.2f} {:>12.2f}".format(
                    tl, e.get("qps", 0) or 0, e.get("avg_latency_us", 0) or 0,
                    e.get("p50_us", 0) or 0, e.get("p99_us", 0) or 0, e.get("p999_us", 0) or 0))
        lines.append("")
    micro = benchmarks.get("micro", {})
    if micro:
        lines.append("  --- Micro Benchmarks ---")
        mresults = micro.get("results", {})
        if isinstance(mresults, dict):
            ps = mresults.get("payload_sweep", {})
            if isinstance(ps, dict) and ps:
                lines.append("  Payload size sweep (threads=32):")
                for psl in sorted(ps.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                    e = ps[psl]
                    if isinstance(e, dict) and e:
                        lines.append(f"    {psl:<18}: QPS={e.get('qps', 'N/A')}, p99={e.get('p99_us', 'N/A')}us")
            cc = mresults.get("connection_sweep", {})
            if isinstance(cc, dict) and cc:
                lines.append("  Connection count sweep (threads=32):")
                for ccl in sorted(cc.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                    e = cc[ccl]
                    if isinstance(e, dict) and e:
                        lines.append(f"    {ccl:<18}: QPS={e.get('qps', 'N/A')}")
        lines.append("")
    summary = data.get("summary", {})
    if summary:
        lines.append("  --- Overall Summary ---")
        if "avg_qps" in summary: lines.append(f"    Avg QPS:              {summary['avg_qps']}")
        if "max_qps" in summary: lines.append(f"    Max QPS:              {summary['max_qps']}")
        if "qps_t16" in summary: lines.append(f"    QPS @ t=16:           {summary['qps_t16']}")
        if "p99_t16" in summary: lines.append(f"    p99 @ t=16:           {summary['p99_t16']} us")
        if "avg_p99_us" in summary: lines.append(f"    Avg p99 latency:      {summary['avg_p99_us']} us")
        if "min_p99_us" in summary: lines.append(f"    Min p99 latency:      {summary['min_p99_us']} us")
        if "thread_scaling_ratio" in summary: lines.append(f"    Thread scaling:       {summary['thread_scaling_ratio']}x")
        if "payload_avg_qps" in summary: lines.append(f"    Payload avg QPS:      {summary['payload_avg_qps']}")
        lines.append("")
    lines.append("=" * 70)
    lines.append("  Report generated by brpc Performance Benchmark Workflow")
    lines.append("=" * 70)
    summary_text = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary_text)
    print(summary_text)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)
    generate_summary(sys.argv[1], sys.argv[2])
