#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 70)
    lines.append("  Apache Spark ARM64 Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Timestamp: {data.get('timestamp', 'N/A')}")
    lines.append("")

    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:   {env.get('architecture', 'N/A')}")
        lines.append(f"  CPU Model:      {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:      {env.get('cores', 'N/A')}")
        lines.append(f"  Memory (MB):    {env.get('memory_mb', 'N/A')}")
        lines.append(f"  Spark Version:  {env.get('software_version', 'N/A')}")
        lines.append(f"  Java Version:   {env.get('java_version', 'N/A')}")
        lines.append(f"  Python Version: {env.get('python_version', 'N/A')}")
        lines.append(f"  OS:             {env.get('os', 'N/A')}")
        lines.append("")

    tpcds = data.get("primary_benchmark", {})
    if tpcds:
        lines.append("  --- TPC-DS Benchmark (Primary, SF={sf}GB) ---".format(
            sf=tpcds.get("scale_factor_gb", "N/A")))
        lines.append(f"  Description:    {tpcds.get('description', 'N/A')}")
        lines.append(f"  Reference:      {tpcds.get('reference', 'N/A')}")
        lines.append(f"  Successful:     {tpcds.get('successful_queries', 'N/A')} / {tpcds.get('total_queries', 'N/A')}")
        lines.append(f"  Total time:     {tpcds.get('total_elapsed_s', 'N/A')}s")
        lines.append(f"  Throughput:     {tpcds.get('throughput_qph', 'N/A')} queries/hour")
        lines.append(f"  Avg query time: {tpcds.get('avg_query_time_ms', 'N/A')}ms")
        lines.append(f"  Avg latency:    {tpcds.get('avg_latency_ms', 'N/A')}ms")
        lines.append("")
        for q in tpcds.get("results", []):
            status = q.get("status", "N/A")
            elapsed = q.get("elapsed_ms", "N/A")
            lines.append(f"    {q.get('query', 'N/A')}: {elapsed}ms [{status[:20]}]")
        lines.append("")

    streaming = data.get("secondary_benchmark", {})
    if streaming:
        lines.append("  --- Structured Streaming Benchmark (Secondary) ---")
        lines.append(f"  Description:    {streaming.get('description', 'N/A')}")
        lines.append(f"  Rate:           {streaming.get('rows_per_second', 'N/A')} rows/s")
        lines.append(f"  Duration:        {streaming.get('duration_seconds', 'N/A')}s")
        lines.append(f"  Total rows:      {streaming.get('total_rows_processed', 'N/A')}")
        lines.append(f"  Avg throughput:  {streaming.get('avg_throughput_records_per_s', 'N/A')} rec/s")
        lines.append(f"  Avg latency:     {streaming.get('avg_latency_ms', 'N/A')}ms")
        lines.append("")

    micro = data.get("micro_benchmark", {})
    if micro:
        lines.append("  --- Micro-Benchmarks ---")
        lines.append(f"  Description:    {micro.get('description', 'N/A')}")
        lines.append(f"  Reference:      {micro.get('reference', 'N/A')}")
        lines.append(f"  Data size:      {micro.get('data_size_rows', 'N/A')} rows")
        lines.append(f"  Avg latency:    {micro.get('avg_latency_ms', 'N/A')}ms")
        lines.append("")
        for test in micro.get("results", []):
            lines.append(f"  {test.get('test', 'N/A')}:")
            lines.append(f"    Avg time:       {test.get('avg_elapsed_ms', 'N/A')}ms")
            lines.append(f"    Avg throughput: {test.get('avg_throughput_records_per_s', 'N/A')} rec/s")
            lines.append(f"    Avg latency:    {test.get('avg_latency_ms', 'N/A')}ms/record")
            lines.append("")

    mllib = data.get("mllib_benchmark", {})
    if mllib:
        lines.append("  --- MLlib Benchmarks ---")
        lines.append(f"  Description:    {mllib.get('description', 'N/A')}")
        lines.append(f"  Data size:      {mllib.get('data_size_samples', 'N/A')} samples")
        lines.append("")
        for test in mllib.get("results", []):
            lines.append(f"  {test.get('test', 'N/A')}:")
            lines.append(f"    Avg train time:  {test.get('avg_train_time_ms', 'N/A')}ms")
            lines.append(f"    Avg predict:     {test.get('avg_predict_time_ms', 'N/A')}ms")
            lines.append("")

    lines.append("=" * 70)
    lines.append("  Report generated by Spark ARM64 Performance Benchmark Workflow")
    lines.append("=" * 70)

    summary = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary)
    print(summary)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)

    input_json = sys.argv[1]
    output_file = sys.argv[2]
    generate_summary(input_json, output_file)
