#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 70)
    lines.append("  Redis Source Build & Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")

    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  Redis Version:     {env.get('software_version', 'N/A')}")
        lines.append(f"  Python Version:    {env.get('python_version', 'N/A')}")
        lines.append(f"  GCC Version:       {env.get('gcc_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:            {env.get('kernel', 'N/A')}")
        lines.append("")

    kv = data.get("primary_benchmark", {})
    if kv:
        lines.append("  --- KV Store Benchmark (Primary) ---")
        lines.append(f"  Description:       {kv.get('description', 'N/A')}")
        lines.append(f"  Reference:         {kv.get('reference', 'N/A')}")
        params = kv.get("parameters", {})
        lines.append(f"  Num operations:    {params.get('num_ops', 'N/A')}")
        lines.append(f"  Value size:        {params.get('value_size_bytes', 'N/A')} bytes")
        lines.append(f"  Iterations:        {params.get('iterations', 'N/A')}")
        lines.append("")
        results = kv.get("results_summary", {})
        for wl, res in results.items():
            if isinstance(res, dict):
                lines.append(f"  {wl}:")
                lines.append(f"    Total ops/s:     {res.get('total_ops_per_sec', 'N/A')}")
                lines.append(f"    Write ops/s:     {res.get('write_ops_per_sec', 'N/A')}")
                lines.append(f"    Read ops/s:      {res.get('read_ops_per_sec', 'N/A')}")
                lines.append(f"    Write MB/s:      {res.get('write_speed_mbs', 'N/A')}")
                lines.append(f"    Read MB/s:       {res.get('read_speed_mbs', 'N/A')}")
                lines.append(f"    Write latency:   {res.get('write_latency_us', 'N/A')} us")
                lines.append(f"    Read latency:    {res.get('read_latency_us', 'N/A')} us")
                lines.append("")

    micro = data.get("micro_benchmark", {})
    if micro:
        mparams = micro.get("parameters", {})
        lines.append("  --- Micro Benchmarks ---")
        lines.append(f"  Description:       {micro.get('description', 'N/A')}")
        lines.append(f"  Value size:        {mparams.get('value_size_bytes', 'N/A')} bytes")
        lines.append(f"  Num ops:           {mparams.get('num_ops', 'N/A')}")
        lines.append(f"  Max threads:       {mparams.get('max_threads', 'N/A')}")
        lines.append("")
        results = micro.get("results", {})
        if isinstance(results, dict):
            cmds = results.get("single_commands", {})
            if cmds:
                lines.append("  Single Commands:")
                for cmd, res in cmds.items():
                    if isinstance(res, dict):
                        lines.append(f"    {cmd}: {res.get('ops_per_sec', 'N/A')} ops/s, "
                                     f"{res.get('latency_us', 'N/A')} us, "
                                     f"{res.get('speed_mbs', 'N/A')} MB/s")
                lines.append("")

            pipe = results.get("pipeline", {})
            if pipe:
                lines.append("  Pipeline Throughput:")
                for ps, res in pipe.items():
                    if isinstance(res, dict):
                        lines.append(f"    {ps}: {res.get('ops_per_sec', 'N/A')} ops/s, "
                                     f"{res.get('latency_per_cmd_us', 'N/A')} us/cmd")
                lines.append("")

            mt = results.get("multithread_scaling", {})
            if mt:
                lines.append("  Multi-Client Scaling:")
                for tc, res in mt.items():
                    if isinstance(res, dict):
                        lines.append(f"    {tc}: write {res.get('write_ops_per_sec', 'N/A')} ops/s, "
                                     f"read {res.get('read_ops_per_sec', 'N/A')} ops/s")
                lines.append("")

    lines.append("=" * 70)
    lines.append("  Report generated by Redis Source Build & Performance Benchmark Workflow")
    lines.append("=" * 70)

    summary = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary)
    print(summary)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)

    input_json = sys.argv[1]
    output_file = sys.argv[2]
    generate_summary(input_json, output_file)