#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)
    lines = []
    lines.append("=" * 70)
    lines.append("  Bolt (bytedance) Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")
    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  Bolt Version:      {env.get('software_version', 'N/A')}")
        lines.append(f"  GCC Version:       {env.get('gcc_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:           {env.get('kernel', 'N/A')}")
        lines.append("")
    benchmarks = data.get("benchmarks", {})
    primary = benchmarks.get("primary", {})
    if primary:
        lines.append("  --- Bolt Acceleration Benchmark (Primary) ---")
        lines.append(f"  Description:       {primary.get('description', 'N/A')}")
        lines.append("")
        rs = primary.get("results_summary", {})
        for name in sorted(rs.keys()):
            e = rs[name]
            if not isinstance(e, dict):
                continue
            lines.append(f"  [{name}]")
            if "size_bytes" in e:
                lines.append(f"    Library size:    {e.get('size_bytes', 'N/A')} bytes ({e.get('size_mb', 'N/A')} MB)")
            if "size_mb" in e:
                pass  # already shown
            if "compile_ok" in e:
                lines.append(f"    Link test:       {'PASS' if e.get('compile_ok') else 'FAIL'}")
                if e.get("link_test_ops_per_sec"):
                    lines.append(f"    Link test ops:   {e['link_test_ops_per_sec']} ops/sec")
            if "passed" in e:
                lines.append(f"    Passed:          {e.get('passed', 'N/A')}")
                if e.get("ops_per_sec"):
                    lines.append(f"    Ops/sec:         {e.get('ops_per_sec')}")
            if "error" in e:
                lines.append(f"    Error:           {e['error'][:80]}")
            lines.append("")
    micro = benchmarks.get("micro", {})
    if micro:
        lines.append("  --- Micro Benchmarks ---")
        mresults = micro.get("results", {})
        if isinstance(mresults, dict):
            la = mresults.get("library_analysis", {})
            if isinstance(la, dict) and la:
                lines.append(f"  Library analysis:")
                lines.append(f"    Size:            {la.get('lib_size_bytes', 'N/A')} bytes")
                lines.append(f"    Symbols:         {la.get('symbol_count', 'N/A')}")
                lines.append(f"    Defined:         {la.get('defined_symbols', 'N/A')}")
                lines.append(f"    Undefined:       {la.get('undefined_symbols', 'N/A')}")
            bs = mresults.get("binary_scan", {})
            if isinstance(bs, dict) and bs:
                lines.append(f"  Binary scan:")
                lines.append(f"    Total binaries:  {bs.get('total_binaries', 'N/A')}")
                lines.append(f"    Tested:          {bs.get('binaries_tested', 'N/A')}")
                lines.append(f"    Passed:          {bs.get('binaries_passed', 'N/A')}")
                lines.append(f"    Failed:          {bs.get('binaries_failed', 'N/A')}")
        lines.append("")
    summary = data.get("summary", {})
    if summary:
        lines.append("  --- Overall Summary ---")
        if "lib_size_mb" in summary: lines.append(f"    Library size:         {summary['lib_size_mb']} MB")
        if "link_test_passed" in summary: lines.append(f"    Link test:            {'PASS' if summary['link_test_passed'] else 'FAIL'}")
        if "link_test_ops_per_sec" in summary: lines.append(f"    Link test ops/sec:    {summary['link_test_ops_per_sec']}")
        if "symbol_count" in summary: lines.append(f"    Symbol count:         {summary['symbol_count']}")
        if "total_binaries" in summary: lines.append(f"    Total binaries:       {summary['total_binaries']}")
        if "binaries_passed" in summary: lines.append(f"    Binaries passed:      {summary['binaries_passed']}")
        lines.append("")
    lines.append("=" * 70)
    lines.append("  Report generated by Bolt Performance Benchmark Workflow")
    lines.append("=" * 70)
    summary_text = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary_text)
    print(summary_text)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)
    generate_summary(sys.argv[1], sys.argv[2])
