#!/usr/bin/env python3
import argparse
import json
import os

PASS_MARK = "[PASS]"
FAIL_MARK = "[FAIL]"

def format_threshold_check(name, actual, threshold, unit, pass_result):
    mark = PASS_MARK if pass_result else FAIL_MARK
    return "{} {}: {} {} (threshold: {} {})".format(mark, name, actual, unit, threshold, unit)

def main():
    parser = argparse.ArgumentParser(description="Generate text summary")
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    with open(args.input) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 60)
    lines.append("Apache Flink ARM64 Performance Benchmark Report")
    lines.append("=" * 60)
    lines.append("")
    lines.append("Software:       Apache Flink v{}".format(data.get("version", "unknown")))
    lines.append("Architecture:   {}".format(data.get("architecture", "arm64")))
    lines.append("Timestamp:      {}".format(data.get("timestamp", "unknown")))
    lines.append("")

    env = data.get("environment", {})
    if env:
        lines.append("--- Environment Info ---")
        lines.append("OS:             {}".format(env.get("os", "unknown")))
        lines.append("Kernel:         {}".format(env.get("kernel", "unknown")))
        lines.append("CPU:            {}".format(env.get("cpu_model", "unknown")))
        lines.append("Cores:          {}".format(env.get("cores", "unknown")))
        lines.append("Memory:         {} MB".format(env.get("memory_mb", "unknown")))
        lines.append("Java:           {}".format(env.get("java_version", "unknown")))
        lines.append("")

    summary = data.get("summary", {})
    thresholds = data.get("thresholds", {})

    lines.append("--- Threshold Checks ---")
    tpcds_t = summary.get("tpcds_avg_throughput_ops_per_sec", 0)
    tpcds_min = thresholds.get("tpcds_min_throughput_ops_per_sec", 500)
    lines.append(format_threshold_check(
        "TPC-DS Throughput", tpcds_t, tpcds_min, "ops/sec", summary.get("tpcds_pass", False)
    ))

    stream_t = summary.get("streaming_avg_throughput_events_per_sec", 0)
    stream_min = thresholds.get("streaming_min_throughput_events_per_sec", 10000)
    lines.append(format_threshold_check(
        "Streaming Throughput", stream_t, stream_min, "events/sec", summary.get("streaming_pass", False)
    ))

    stream_l = summary.get("streaming_avg_latency_ms", 0)
    stream_max_l = thresholds.get("streaming_max_latency_ms", 500)
    lines.append(format_threshold_check(
        "Streaming Latency", stream_l, stream_max_l, "ms",
        stream_l <= stream_max_l
    ))

    overall = summary.get("overall_pass", False)
    lines.append("")
    lines.append("--- Overall Result ---")
    lines.append("{} {}".format(PASS_MARK if overall else FAIL_MARK, "OVERALL: All thresholds passed" if overall else "OVERALL: Some thresholds not met"))
    lines.append("")

    micro_ops = summary.get("micro_operations", {})
    if micro_ops:
        lines.append("--- Micro Benchmarks ---")
        for op_id, op_data in micro_ops.items():
            lines.append("  {}: {} ops/sec, {} ms latency ({})".format(
                op_data.get("name", op_id),
                op_data.get("throughput", 0),
                op_data.get("latency", 0),
                op_data.get("category", "unknown")
            ))
        lines.append("")

    lines.append("=" * 60)
    lines.append("Generated by flink ARM64 performance benchmark")
    lines.append("=" * 60)

    with open(args.output, "w") as f:
        f.write("\n".join(lines))

    print("[SUMMARY] Text summary written to {}".format(args.output))

if __name__ == "__main__":
    main()