#!/usr/bin/env python3
import argparse
import json
import os

PASS_MARK = "[PASS]"
FAIL_MARK = "[FAIL]"

TPCDS_MIN_THROUGHPUT = 500
STREAMING_MIN_THROUGHPUT = 10000
STREAMING_MAX_LATENCY = 500

def format_threshold_check(name, actual, threshold, unit, pass_result):
    mark = PASS_MARK if pass_result else FAIL_MARK
    return "{} {}: {} {} (threshold: {} {})".format(mark, name, actual, unit, threshold, unit)

def main():
    parser = argparse.ArgumentParser(description="Generate text summary from results.json")
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    with open(args.input) as f:
        data = json.load(f)

    lines = []
    lines.append("=" * 60)
    lines.append("Apache Flink ARM64 Performance Benchmark Report")
    lines.append("=" * 60)
    lines.append("")
    lines.append("Software:       Apache Flink v{}".format(data.get("version", "unknown")))
    lines.append("Architecture:   {}".format(data.get("architecture", "arm64")))
    lines.append("Timestamp:      {}".format(data.get("timestamp", "unknown")))
    lines.append("")

    vi = data.get("version_info", {})
    if vi:
        lines.append("--- Environment Info ---")
        lines.append("OS:             {}".format(vi.get("os", "unknown")))
        lines.append("Kernel:         {}".format(vi.get("kernel", "unknown")))
        lines.append("CPU:            {}".format(vi.get("cpu_model", "unknown")))
        lines.append("Cores:          {}".format(vi.get("cores", "unknown")))
        lines.append("Memory:         {} MB".format(vi.get("memory_mb", "unknown")))
        lines.append("Java:           {}".format(vi.get("java_version", "unknown")))
        lines.append("")

    lines.append("--- Threshold Checks ---")

    primary = data.get("primary_benchmark", {})
    tpcds_avg = primary.get("average_throughput_ops_per_sec", 0)
    tpcds_pass = tpcds_avg >= TPCDS_MIN_THROUGHPUT
    lines.append(format_threshold_check(
        "TPC-DS Throughput", tpcds_avg, TPCDS_MIN_THROUGHPUT, "ops/sec", tpcds_pass
    ))

    secondary = data.get("secondary_benchmark", {})
    stream_avg_t = secondary.get("average_throughput_events_per_sec", 0)
    stream_avg_l = secondary.get("average_latency_ms", 0)
    stream_pass = stream_avg_t >= STREAMING_MIN_THROUGHPUT and stream_avg_l <= STREAMING_MAX_LATENCY
    lines.append(format_threshold_check(
        "Streaming Throughput", stream_avg_t, STREAMING_MIN_THROUGHPUT, "events/sec", stream_avg_t >= STREAMING_MIN_THROUGHPUT
    ))
    lines.append(format_threshold_check(
        "Streaming Latency", stream_avg_l, STREAMING_MAX_LATENCY, "ms", stream_avg_l <= STREAMING_MAX_LATENCY
    ))

    tpcds_pass_val = primary.get("pass", tpcds_pass)
    stream_pass_val = secondary.get("pass", stream_pass)
    overall_pass = tpcds_pass_val and stream_pass_val

    lines.append("")
    lines.append("--- Overall Result ---")
    lines.append("{} {}".format(PASS_MARK if overall_pass else FAIL_MARK, "OVERALL: All thresholds passed" if overall_pass else "OVERALL: Some thresholds not met"))
    lines.append("")

    micro = data.get("micro_benchmark", {})
    micro_results = micro.get("results", [])
    if micro_results:
        lines.append("--- Micro Benchmarks ---")
        for op in micro_results:
            lines.append("  {}: {} ops/sec, {} ms latency ({})".format(
                op.get("name", op.get("operation_id", "unknown")),
                op.get("average_throughput_ops_per_sec", 0),
                op.get("average_latency_ms", 0),
                op.get("category", "unknown")
            ))
        lines.append("")

    lines.append("=" * 60)
    lines.append("Generated by flink ARM64 performance benchmark")
    lines.append("=" * 60)

    with open(args.output, "w") as f:
        f.write("\n".join(lines))

    print("[SUMMARY] Text summary written to {}".format(args.output))

if __name__ == "__main__":
    main()
