#!/usr/bin/env python3
import sys
import json
from datetime import datetime, timezone


def generate_summary(input_json, output_file):
    with open(input_json) as f:
        data = json.load(f)
    lines = []
    lines.append("=" * 70)
    lines.append("  Golang Performance Benchmark Report")
    lines.append("=" * 70)
    lines.append(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"  Test Time: {data.get('test_time', data.get('timestamp', 'N/A'))}")
    lines.append("")
    env = data.get("environment", {})
    if env:
        lines.append("  --- Environment ---")
        lines.append(f"  Architecture:      {env.get('architecture', 'N/A')}")
        lines.append(f"  Model:             {env.get('Model', 'N/A')}")
        lines.append(f"  CPU Model:         {env.get('cpu_model', 'N/A')}")
        lines.append(f"  CPU Cores:         {env.get('cpu_cores', 'N/A')}")
        lines.append(f"  Go Version:        {env.get('software_version', 'N/A')}")
        lines.append(f"  OS:                {env.get('os', 'N/A')}")
        lines.append(f"  Kernel:           {env.get('kernel', 'N/A')}")
        lines.append("")
    benchmarks = data.get("benchmarks", {})
    primary = benchmarks.get("primary", {})
    if primary:
        lines.append("  --- Go stdlib Benchmarks (Primary) ---")
        lines.append(f"  Description:       {primary.get('description', 'N/A')}")
        params = primary.get("parameters", {})
        lines.append(f"  Packages:          {params.get('packages', 'N/A')}")
        lines.append(f"  CGO:               {params.get('cgo_enabled', 'N/A')}")
        lines.append("")
        rs = primary.get("results_summary", {})
        header = "    {:<35} {:>10} {:>12} {:>10}".format("benchmark", "ns/op", "ops/sec", "allocs")
        lines.append(header)
        lines.append("    " + "-" * (len(header) - 4))
        for name in sorted(rs.keys()):
            e = rs[name]
            if isinstance(e, dict) and e:
                lines.append("    {:<35} {:>10.2f} {:>12.2f} {:>10.2f}".format(
                    name[:35], e.get("ns_per_op", 0) or 0, e.get("ops_per_sec", 0) or 0, e.get("allocs_per_op", 0) or 0))
        lines.append("")
    micro = benchmarks.get("micro", {})
    if micro:
        lines.append("  --- Micro Benchmarks ---")
        mresults = micro.get("results", {})
        if isinstance(mresults, dict):
            ts = mresults.get("thread_scaling", {})
            if isinstance(ts, dict) and ts:
                lines.append("  Thread scaling (GOMAXPROCS):")
                for bench_name in sorted(ts.keys()):
                    cpu_data = ts[bench_name]
                    if not isinstance(cpu_data, dict):
                        continue
                    lines.append(f"    [{bench_name[:40]}]")
                    for cpu_label in sorted(cpu_data.keys(), key=lambda x: int(''.join(c for c in x if c.isdigit()) or 0)):
                        e = cpu_data[cpu_label]
                        if isinstance(e, dict) and e:
                            lines.append(f"      {cpu_label:<10}: {e.get('ns_per_op', 'N/A')} ns/op, {e.get('ops_per_sec', 'N/A')} ops/sec")
        lines.append("")
    summary = data.get("summary", {})
    if summary:
        lines.append("  --- Overall Summary ---")
        if "avg_ns_per_op" in summary: lines.append(f"    Avg ns/op:           {summary['avg_ns_per_op']}")
        if "min_ns_per_op" in summary: lines.append(f"    Min ns/op (fastest): {summary['min_ns_per_op']}")
        if "max_ns_per_op" in summary: lines.append(f"    Max ns/op (slowest): {summary['max_ns_per_op']}")
        if "avg_ops_per_sec" in summary: lines.append(f"    Avg ops/sec:         {summary['avg_ops_per_sec']}")
        if "max_ops_per_sec" in summary: lines.append(f"    Max ops/sec:         {summary['max_ops_per_sec']}")
        if "avg_allocs_per_op" in summary: lines.append(f"    Avg allocs/op:       {summary['avg_allocs_per_op']}")
        for k, v in summary.items():
            if k.endswith("_thread_scaling_ratio"):
                lines.append(f"    {k.replace('_thread_scaling_ratio', '')} thread scaling: {v}x")
        lines.append("")
    lines.append("=" * 70)
    lines.append("  Report generated by Golang Performance Benchmark Workflow")
    lines.append("=" * 70)
    summary_text = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(summary_text)
    print(summary_text)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_summary.py <input_json> <output_file>")
        sys.exit(1)
    generate_summary(sys.argv[1], sys.argv[2])
